baseURL = "https://adoring-lichterman-c1c186.netlify.app"
languageCode = "en-us"
title = "South Asian Network Operators Group"
theme = "sanog"
uglyurls = true

[markup.goldmark.renderer]
unsafe= true
